apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: llm-system-jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
  ingress:
    enabled: true
    hosts:
      - jaeger.llm-system.local
  agent:
    strategy: DaemonSet
  collector:
    replicas: 2
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi 