apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  POSTGRES_USER: "llm_admin"
  POSTGRES_PASSWORD: "${DB_PASSWORD}"
  POSTGRES_DB: "llm_enterprise"
  DB_CONNECTION_STRING: "postgresql://llm_admin:${DB_PASSWORD}@postgres:5432/llm_enterprise"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_TLS_CERT: |
    -----BEGIN CERTIFICATE-----
    ${REDIS_CERT}
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: llm-api-keys
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
  DEEPSEEK_API_KEY: "${DEEPSEEK_API_KEY}"
  QWEN_API_KEY: "${QWEN_API_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  JWT_SECRET_KEY: "${JWT_SECRET}"
  JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
  JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-certificates
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: kubernetes.io/tls
data:
  tls.crt: ${BASE64_SSL_CERT}
  tls.key: ${BASE64_SSL_KEY}
  ca.crt: ${BASE64_CA_CERT}
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-credentials
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
  PROMETHEUS_AUTH_TOKEN: "${PROMETHEUS_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_KEY}"
  BACKUP_ENCRYPTION_KEY: "${BACKUP_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  MINIO_ROOT_USER: "minio_admin"
  MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: llm-enterprise
  labels:
    app.kubernetes.io/part-of: llm-processing-system
    security.sensitive: "true"
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_PASSWORD}"
  KEYCLOAK_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
  KEYCLOAK_TLS_KEYSTORE_PASSWORD: "${KEYCLOAK_TLS_PASSWORD}"