global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'task-manager:8084']

  - job_name: 'llm-engine'
    static_configs:
      - targets: ['llm-engine:5000'] 