scrape_configs:
- job_name: minio-job
  bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4OTM2NjcxMTZ9.CDV7DEpORuLoOs-xZI3OeFliw35rzhElmyGsT-omzDy-JvKgtTjN15qIGKlxL1I5HXVD1Xa9q2d7ZFq3_69g9w
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['localhost:9000']
