_format_version: "2.1"
_transform: true

services:
  - name: task-service
    url: http://task-manager:8081
    routes:
      - name: task-routes
        paths:
          - /api/tasks
        strip_path: false
    plugins:
      # - name: jwt
      #   config:
      #     key_claim_name: kid
      #     claims_to_verify:
      #       - exp
      - name: key-auth
        config:
          key_names:
            - X-API-KEY
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
          exposed_headers:
            - Authorization
          credentials: true
          max_age: 3600

  - name: auth-service
    url: http://auth-service:8082
    routes:
      - name: auth-routes
        paths:
          - /api/auth
        strip_path: false
