spring:
  application:
    name: api-gateway  
  cloud:
    gateway:
      routes:
        - id: task-manager
          uri: lb://task-manager
          predicates:
            - Path=/api/tasks/**
          filters:
            - RewritePath=/api/tasks/(?<segment>.*), /$\{segment}
            
        - id: validator 
          uri: lb://validator
          predicates:
            - Path=/api/validator/**
            
        - id: llm-engine
          uri: lb://llm-engine
          predicates:
            - Path=/api/llm/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
